PLAYER_IDLE :: Karakuri.Animation.{
    name         = "idle",
    texture_path = "examples/shmup/textures/player_idle.png",
    frame_count  = 1,
    frame_rate   = 1,
    looping      = true,
};

PLAYER_STRAFE_FORWARD :: Karakuri.Animation.{
    name         = "strafe_forward",
    texture_path = "examples/shmup/textures/player_strafe_forward.png",
    frame_count  = 3,
    frame_rate   = 8,
    looping      = false,
};

PLAYER_STRAFE_RIGHT :: Karakuri.Animation.{
    name         = "strafe_right",
    texture_path = "examples/shmup/textures/player_strafe_right.png",
    frame_count  = 6,
    frame_rate   = 16,
    looping      = false,
};

PLAYER_STRAFE_LEFT :: Karakuri.Animation.{
    name         = "strafe_left",
    texture_path = "examples/shmup/textures/player_strafe_left.png",
    frame_count  = 6,
    frame_rate   = 16,
    looping      = false,
};
