#!/bin/sh

echo "Checking build..."
if ! jai ./build_example.jai - shmup; then
    echo "❌ Commit blocked: Build failed."
    exit 1
fi

BLOCK_MARKER="no_commit"

echo "Checking for no_commit..."
if git diff --cached --diff-filter=ACM | grep -F @"$BLOCK_MARKER"; then
    echo "❌ Commit blocked: Found '$BLOCK_MARKER' in staged changes."
    exit 1
fi

echo "Running tests..."
if ! jai ./test.jai; then
    echo "❌ Commit blocked: Tests don't pass."
    exit 1
fi

exit 0
