Maybe :: #import "Maybe";

#load "engine.jai";
#load "components.jai";
#load "entity.jai";
#load "scene.jai";
#load "input.jai";

get_behavior :: world_get_downcasted_behavior;
get_entity_with_name :: world_get_entity_with_name;
get_entity_with_token :: world_get_entity_with_token;
get_entities_with_tag :: world_get_entities_with_tag;
get_render_size :: get_render_dimensions;

#scope_module

#load "signature.jai";
#load "world.jai";
