name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install raylib
      run: sudo add-apt-repository ppa:texus/raylib -y && sudo apt install libraylib5-dev -y
    - name: Run build
      run: cargo build --workspace --verbose

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install raylib
      run: sudo add-apt-repository ppa:texus/raylib -y && sudo apt install libraylib5-dev -y
    - name: Run tests
      run: cargo test --workspace --verbose

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install raylib
      run: sudo add-apt-repository ppa:texus/raylib -y && sudo apt install libraylib5-dev -y
    - name: Run clippy
      run: cargo clippy -- -D warnings

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run rustfmt
      run: cargo fmt --all --check

  test_docs:
    name: Test docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run doc tests
      run: cargo test --workspace --doc
