name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install raylib
        run: sudo add-apt-repository ppa:texus/raylib -y && sudo apt install libraylib5-dev libglfw3-dev libxinerama-dev libxcursor-dev libxi-dev -y
      - name: Run tests
        run: cargo test --workspace --verbose

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install raylib
        run: sudo add-apt-repository ppa:texus/raylib -y && sudo apt install libraylib5-dev libglfw3-dev libxinerama-dev libxcursor-dev libxi-dev -y
      - name: Run clippy
        run: cargo clippy -- -D warnings

  coverage:
    name: Coverage
    environment: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install raylib
        run: sudo add-apt-repository ppa:texus/raylib -y && sudo apt install libraylib5-dev libglfw3-dev libxinerama-dev libxcursor-dev libxi-dev -y
      - name: Install tarpaulin
        run: cargo install tarpaulin
      - name: Generate coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: cargo tarpaulin --verbose --all-features --workspace --timeout 120 --coveralls COVERALLS_TOKEN --out html

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run rustfmt
        run: cargo fmt --all --check
